import Hero from "@/components/service/Hero";
import React, { useEffect, useState } from "react";
import Image from "next/image";
import Payperclick from "@/components/service/Payperclick";
import MarketingCompanies from "@/components/service/MarketingCompanies";
import KeyServeice from "@/components/KeyServeice";
import { useRouter } from "next/router";
import MarketingPlanCta from "@/components/service/MarketingPlanCta";
import OthersSite from "@/components/service/OthersSite";
import ConversionMarketing from "@/components/service/ConversionMarketing";
import DedicatedTeam from "@/components/DedicatedTeam";
import FaqSection from "@/components/service/FaqSection";
import OurWork from "@/components/service/OurWork";
import ListOfServeice from "@/components/service/ListOfServeice";
import Head from "next/head";
import FooterTopCta from "@/components/FooterTopCta";
import ReportGraph from "@/components/ReportGraph";
import CaseStudySection from "@/components/CaseStudySection";
import TestimonialCarousel from "@/components/TestimonialCarousel";

function PpcAgency(props) {
	const [companies, setCompanies] = useState(props.companiesData);
	const [keyserveice, setKeyserveice] = useState(props.keyServeice);
	const [faqSection, setFaqSection] = useState(props.faqData);
	const [ourWork, setourWork] = useState(props.ourWork);
	const [listOfServeice, setListOfServeice] = useState(props.listOfServeiceData);
	const [caseCard, setCaseCard] = useState(props.cardData);

	// useEffect(() => {
	// 	fetch('http://localhost:3000/api/companies')
	// 	.then(res => res.json())
	// 	.then(data => setCompanies(data))

	//   }, [])

	return (
		<div className="section_body overflow-x-hidden">
			<Head>
				<title>Top PPC Agency</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				{/* <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" /> */}
				<link rel="icon" href="/infinity.svg" />
			</Head>
			<Hero
				firstPic="/serveice/ppc-agency-hero-left-escape-room-marketer-01.svg"
				secondPic="/serveice/ppc-agency-hero-right-escape-room-marketer-01.svg"
				title="We’re The PPC Agency That Puts More Dollars In Your Pocket"
				pera="Increase your conversion rates to lower your cost per conversion and get a higher conversion volume. All leading to more revenue as well."
			/>
			<OurWork ourWorkData={ourWork} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<Payperclick
				bodyColor="bg-[var(--section-bg-lightred)]"
				title="We Find More Pay-Per-Click Improvements In 5 Minutes Than Others Take Weeks "
				pera="Increase your conversion rates to lower your cost per conversion and get a higher conversion volume. All leading to more revenue as well."
			/>
			{/* <div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] rotate-180"></div>
			<MarketingCompanies companiesData={companies} /> */}
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center "></div>
			<CaseStudySection caseStudyCard={caseCard} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<ListOfServeice
				listOfServeiceData={listOfServeice}
				bodyColor="bg-[var(--section-bg-lightred)]"
				mobileImage="ppcagency/escaperoom-marketer-ppc-agency-list.svg"
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center"></div>
			<KeyServeice bodyColor="bg-[var(--section-bg-lightblue)]" cardColor="bg-[#ffffff]" keyServeiceData={keyserveice} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<MarketingPlanCta
				bodyColor="bg-[var(--section-bg-lightred)]"
				title="Your Custom Marketing Plan Shows The Exact Steps We’ll Take To Hit Your Goals"
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center"></div>
			{/* <OthersSite
				title="Want To Expand To Other PPC Channels?  We Got You "
				pera="We can start where you're at, crush every goal you have, and then help you expand."
			/> */}

			<ConversionMarketing
				bodyColor="bg-[var(--section-bg-lightblue)]"
				cardColor="bg-white"
				title="Improve One Channel or Rapidly Scale Performance Across All of Them at Once"
				pera="Work with specialized teams that rapidly adapt, expand, and scale as one cohesive unit."
				conversionRateOptimization
				emailMarketing
				searchEngineOptimization
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<DedicatedTeam
				bodyColor="bg-[var(--section-bg-lightred)]"
				title="Meet Your Dedicated Team Before We Start Making You More Money"
				pera="Be confident in the people behind your marketing.Test their experience, their approach, and their humor."
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center"></div>
			<ReportGraph
				bodyColor="bg-[var(--section-bg-lightblue)]"
				title="Reporting & Communication Tailored Exactly How You Want It"
				pera="Choose from custom dashboards and scheduled meetings to quick texts or Slack. If you're into it, we're into it."
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<FaqSection bodyColor="bg-[var(--section-bg-lightred)]" faqSectionData={faqSection} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center"></div>
			<TestimonialCarousel
				text1="I've tried other SEO agencies before, but Escape Room Marketer truly stands out. Their team not only boosted our search engine rankings but also provided personalized recommendations to improve our website. Our bookings have never been better. They've earned my trust and loyalty!"
				text2=""
				name1={{ name: "patel", designation: "owner" }}
			/>
			<FooterTopCta pageBreakBlue={true} />
		</div>
	);
}

export const getServerSideProps = async () => {
	let data = await fetch("http://localhost:3000/api/companies?slug=ppcAgency");
	let companiesData = await data.json();

	let keyserveicedata = await fetch("http://localhost:3000/api/keyserveice?slug=ppcAgency");
	let keyServeice = await keyserveicedata.json();

	let faqSectiondata = await fetch("http://localhost:3000/api/faqsection?slug=ppcAgency");
	let faqData = await faqSectiondata.json();

	let ourWorkData = await fetch("http://localhost:3000/api/ourwork?slug=ppcAgency");
	let ourWork = await ourWorkData.json();

	let listOfServeice = await fetch("http://localhost:3000/api/listofserveice?slug=ppcAgency");
	let listOfServeiceData = await listOfServeice.json();

	let caseData = await fetch("http://localhost:3000/api/casestudycard");
	let cardData = await caseData.json();
	return {
		props: { companiesData, keyServeice, faqData, ourWork, listOfServeiceData, cardData }, // will be passed to the page component as props
	};
};

export default PpcAgency;
