import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/blogdetails.module.css";
import FooterTopCta from "@/components/FooterTopCta";
import moment from "moment";
import Link from "next/link";
import { BiChevronLeft, BiChevronRight } from "react-icons/bi";
import { InfinitySpin } from "react-loader-spinner";

import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote } from "next-mdx-remote";

// export const serializeMarkdown = (item) => {
// 	const description = item?.data.attributes.description;
// 	// console.log(description);
// 	// return {
// 	// 	...item.data,
// 	// 	attributes: {
// 	// 		...item.data.attributes,
// 	// 		description,
// 	// 	},
// 	// };

// 	return description;
// };

function Blogdetails({ source, blogData, allBlogData }) {
	const router = useRouter();
	const postId = router.query.slug;

	console.log(blogData);

	return (
		<div>
			<Head>
				<title>Blog Details</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			{/* {!post && (
				<div className="absolute h-full w-full left-0 right-0 top-0 bottom-0 z-50 bg-[#373737d3] flex justify-center pt-[50vh]">
					<div className="flex gap-2 p-4">
						<div class="bg-[#ffd9cf]  w-4 h-4 rounded-full animate-bounce blue-circle"></div>
						<div class="bg-[#ffc2b3] p-2 w-4 h-4 rounded-full animate-bounce green-circle"></div>
						<div class="bg-[#ff987e] p-2  w-4 h-4 rounded-full animate-bounce red-circle "></div>
					</div>
				</div>
			)} */}
			<div className=" pt-16 md:pt-24 pb-44 bg-[var(--section-bg-lightred)]">
				<div className="nav_container flex md:block justify-center mb-4">
					<Link
						// onClick={backToPreviousPage}
						href="/blog"
						className="text-[#FF492C] hover:text-[#E74329] text-center  font-bold text-base flex items-center  "
					>
						{/* <div className="flex items-center cursor-pointer "> */}
						<BiChevronLeft className="text-2xl" /> Back To All Blog
						{/* </div> */}
					</Link>
				</div>
				<div className=" px-2 md:px-0  m-auto">
					<h1 className="hero_heading text-center max-w-[1200px] ">
						{blogData ? (
							blogData.data.attributes.title
						) : (
							<p>
								Loading <span className=" animate-bounce">.</span>
								<span className="animate-bounce">.</span>
								<span className="animate-bounce">.</span>
							</p>
						)}
					</h1>
				</div>
				<div className=" flex flex-col sm:flex-row justify-center items-center mt-[40px]">
					<div className="flex items-center">
						<div className="bg-[#F1F8FF] h-[30px] w-[30px] sm:h-[40px] sm:w-[40px] flex justify-center items-center rounded-full border-[#FFD8D1] border-[1px] mr-2">
							<Image src="/infinity.svg" height={30} width={25} alt={"this is hero alt"} className="w-[20px] sm:w-[25px]" />
						</div>
						by Escape Room Marketer{" "}
					</div>
					<div className="flex items-center">
						<p className="h-[7px] w-[7px] mx-3 rounded-full bg-[#c7c7c7]"></p>
						<span>Created {moment(blogData && blogData.data.attributes.createdAt).fromNow()} </span>
					</div>
				</div>
				<div className="flex justify-center"></div>
			</div>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center"></div>
			<div className="bg-[var(--section-bg-lightblue)]">
				<div className={styles.blog_details}>
					<div className="pt-16 pb-20 px-5 max-w-[700px] mx-auto list-inside ">
						{blogData && (
							<Image
								src={`${blogData.data.attributes.cover_image.data && blogData.data.attributes.cover_image.data.attributes.url}`}
								height={200}
								width={500}
								className="h-[400px] w-full -mt-[295px] object-cover rounded-t-lg "
								alt={blogData.data.attributes.cover_image.data && blogData.data.attributes.cover_image.data.attributes.alternativeText}
							/>
						)}
						{/* {post && <div className="mt-12" dangerouslySetInnerHTML={{ __html: post.description }} />} */}
						<div className="mt-12">
							<MDXRemote {...source} />
						</div>
					</div>
					{!blogData && (
						<div className="flex justify-center h-[600px]">
							<InfinitySpin width="200" color="#FF492C" />
						</div>
					)}
				</div>
				<div className="more_post">
					<h2 className="text-[24px] md:text-[32px] lg:text-[42px] font-[900] px-5 max-w-[800px] lg:max-w-[1000px] mx-auto text-center pb-[60px]">
						Read more insightful business information that can help you grow your business.
					</h2>
					<div className="pb-12 px-5 max-w-[1200px] mx-auto grid grid-cols-1 md:grid-cols-2 gap-y-12 gap-x-4 justify-center">
						{allBlogData &&
							allBlogData.data
								.filter((item) => item.id !== Number(postId))
								.slice(0, 2)
								.map((post) => {
									return (
										<Link
											href={`/blog/blog-details?slug=${post.id}`}
											key={post.id}
											className="group max-w-[550px] mx-auto bg-[#fff] p-5 shadow-md rounded-md hover:shadow-[0px_0px_40px_1px_rgba(255,73,44,0.15)] duration-300"
										>
											<Image
												src={`${post.attributes.cover_image.data && post.attributes.cover_image.data.attributes.url}`}
												height={200}
												width={550}
												className="h-[280px] object-cover rounded-t-[6px]"
												alt=""
											/>
											<p className="font-[500] text-[20px] lg:text-[24px] pt-4 group-hover:text-[#FF492C]">{post.attributes.title}</p>
										</Link>
									);
								})}
					</div>
					<div className="flex justify-center pb-20 text-[#FF492C]">
						<Link href={"/blog"} className="group flex justify-center font-[600] cursor-pointer">
							All Article <BiChevronRight className={`arrow_rotate pt-[2px] text-2xl group-hover:translate-x-[3px] duration-200`} />
						</Link>
					</div>
				</div>
			</div>
			<FooterTopCta pageBreakBlue={true} />
		</div>
	);
}

// export async function getServerSideProps(context) {
// 	// Fetch data from external API
// 	let data = await fetch(`http://localhost:1337/api/blogs/4?populate=*`);
// 	// let blogData = await data.json();
// 	// Pass data to the page via props
// 	console.log(data);
// 	return {
// 		props: { blogData: await serializeMarkdown(data) },
// 	};
// }

export async function getServerSideProps(context) {
	// MDX text - can be from a local file, database, anywhere
	const postId = context.query.slug;
	const source = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/blogs/${postId}?populate=*`);
	const blogData = await source.json();
	const mdxSource = await serialize(blogData.data.attributes.description);
	const allBlog = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/blogs?populate=*`);
	const allBlogData = await allBlog.json();
	// const allBlogs = await fetch("");
	return { props: { source: mdxSource, blogData, allBlogData } };
}

export default Blogdetails;
